"use client";
import React, { useCallback, useState } from "react";
import { useDropzone } from "react-dropzone";
import { QRCodeSVG } from "qrcode.react";
const MAX_SIZE = 50 * 1024 * 1024;
const ACCEPTED = { "text/html": [".html", ".htm"], "application/pdf": [".pdf"], "application/zip": [".zip"], "image/png": [".png"], "image/jpeg": [".jpg", ".jpeg"], "image/webp": [".webp"] };
function slugify(value: string) { return value.toLowerCase().replace(/\.[^.]+$/, "").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 60); }
export default function DragDropUploader() {
  const [file, setFile] = useState<File | null>(null); const [customSlug, setCustomSlug] = useState(""); const [isUploading, setIsUploading] = useState(false); const [publishedUrl, setPublishedUrl] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const onDrop = useCallback((acceptedFiles: File[]) => { setError(null); const selected = acceptedFiles[0]; if (!selected) return; setFile(selected); setCustomSlug((current) => current || slugify(selected.name)); }, []);
  const { getRootProps, getInputProps, isDragActive } = useDropzone({ onDrop, accept: ACCEPTED, maxFiles: 1, maxSize: MAX_SIZE, onDropRejected: (r) => setError(r[0]?.errors[0]?.message ?? "Unsupported file. Use HTML, PDF, ZIP, PNG, JPG, or WEBP up to 50 MB.") });
  const handleUpload = async () => { if (!file) return; const slug = customSlug.trim().toLowerCase().replace(/[^a-z0-9-]/g, "-").replace(/-+/g, "-").replace(/^-+|-+$/g, ""); if (!slug) { setError("Enter a valid URL slug."); return; } setError(null); setIsUploading(true); try { const bodyData = new FormData(); bodyData.append("file", file); bodyData.append("slug", slug); const res = await fetch("/api/upload", { method: "POST", body: bodyData }); const data = await res.json(); if (!res.ok) throw new Error(data.error || "Upload failed."); setPublishedUrl(data.publishedUrl); } catch (err) { setError(err instanceof Error ? err.message : "Upload failed."); } finally { setIsUploading(false); } };
  const downloadQr = () => { const svg = document.getElementById("pagedrop-qr"); if (!svg || !publishedUrl) return; const source = new XMLSerializer().serializeToString(svg); const blob = new Blob([source], { type: "image/svg+xml;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "pagedrop-qr.svg"; anchor.click(); URL.revokeObjectURL(url); };
  return <div className="mx-auto max-w-2xl rounded-3xl border border-slate-200 bg-white p-6 shadow-xl shadow-slate-200/50 sm:p-8">{!publishedUrl ? <div className="space-y-5"><div {...getRootProps()} className={["rounded-2xl border-2 border-dashed p-10 text-center transition", isDragActive ? "border-indigo-500 bg-indigo-50" : "border-slate-300 bg-slate-50 hover:border-indigo-400 hover:bg-indigo-50/50"].join(" ")}><input {...getInputProps()} /><div className="mx-auto mb-4 grid h-14 w-14 place-items-center rounded-2xl bg-indigo-100 text-2xl">↑</div><p className="font-semibold text-slate-900">{file ? file.name : isDragActive ? "Drop it here" : "Drag & drop your file"}</p><p className="mt-2 text-sm text-slate-500">HTML, PDF, ZIP, PNG, JPG or WEBP · max 50 MB</p></div><div><label htmlFor="slug" className="mb-2 block text-sm font-semibold text-slate-700">Custom link slug</label><div className="flex overflow-hidden rounded-xl border border-slate-300 bg-white focus-within:border-indigo-500"><span className="flex items-center bg-slate-50 px-3 text-sm text-slate-400">yourdomain.com/</span><input id="slug" value={customSlug} onChange={(e) => setCustomSlug(e.target.value)} placeholder="my-menu" className="min-w-0 flex-1 px-3 py-3 outline-none" /></div></div>{error && <p className="rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</p>}<button onClick={handleUpload} disabled={!file || isUploading} className="w-full rounded-xl bg-indigo-600 py-3.5 font-semibold text-white transition hover:bg-indigo-700 disabled:cursor-not-allowed disabled:opacity-50">{isUploading ? "Publishing…" : "Publish instantly"}</button></div> : <div className="space-y-6 text-center"><div><p className="text-sm font-medium text-emerald-600">Published successfully</p><h2 className="mt-1 text-2xl font-bold text-slate-950">Your page is live.</h2></div><a href={publishedUrl} target="_blank" rel="noreferrer" className="break-all font-mono text-sm text-indigo-600 hover:underline">{publishedUrl}</a><div className="mx-auto w-fit rounded-2xl border border-slate-200 bg-white p-4"><QRCodeSVG id="pagedrop-qr" value={publishedUrl} size={220} includeMargin /></div><button onClick={downloadQr} className="rounded-xl border border-slate-300 px-5 py-3 font-semibold text-slate-700 hover:bg-slate-50">Download QR code</button></div>}</div>;
}
